apiVersion: v1
kind: Service
metadata:
  name: hello-app-lb
  labels:
    app: hello-app-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 1337
  selector:
    app: hello-app
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: taeyo/hellonode:v9
        command : ["node", "/var/www/index.js"]
        ports:
        - containerPort: 1337
